### ISSUE TITLE
[Bug]: Search Bar

### ISSUE THREAD

**Issue by sim0511** [Langara-Spiders/alertme#125]
### Description

The search bar should be empty when the route changes along with the marker

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots / Screen Recordings

Paste, drag and drop, or click option below to add your files here.

### OS

iOS, Android

### According to you how serious is the problem

critical

**Comment by sandeepguggilla99** [comment]
Closed
