### ISSUE TITLE
[Bug]: Bottom Sheet Height

### ISSUE THREAD

**Issue by Karthik2506** [Langara-Spiders/alertme#126]
### Description

height is not matching as per the design

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots / Screen Recordings

Paste, drag and drop, or click option below to add your files here.

### OS

iOS, Android

### According to you how serious is the problem

critical

**Comment by sandeepguggilla99** [comment]
Closed
